### ISSUE TITLE
UTF-8 error

### ISSUE THREAD

**Issue by horstepipe** [andrewleech/plugin.video.netflixbmc#13]
Adding episodes containing mutations like "ä,ö,ü" to database results in an error:

14:03:09 T:2896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\horstepipe\AppData\Roaming\XBMC\addons\plugin.video.netflixbmc\default.py", line 1125, in <module>
                                                addSeriesToLibrary(seriesID, name, url)
                                              File "C:\Users\horstepipe\AppData\Roaming\XBMC\addons\plugin.video.netflixbmc\default.py", line 832, in addSeriesToLibrary
                                                filename = (''.join(c for c in filename.encode("utf-8") if c not in '/\\:?"*|<>')).strip(' .')
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by Carst-Tankink** [comment]
A similar exception is thrown when the Viewing Activity contains a UTF-8 (non-ASCII) character. I did some hacking on the code that seems to fix it, I'll post a pull request later today.

**Comment by Carst-Tankink** [comment]
Pull request #14 should handle this bug.

**Comment by horstepipe** [comment]
Works perfect here, thank you!!!
(Win 8.1, Gotham 13.2, German Netflix)
