### ISSUE TITLE
Play/Pause restarts movie on Linux

### ISSUE THREAD

**Issue by walkofdoom** [andrewleech/plugin.video.netflixbmc#15]
Hi,

it seems the behaviour of the Return key while playing a movie has changed.

Return does not Pause/resume the movie, it seems as if the page is reloaded. The space key however does work fine to Pause.

This happens under Google Chrome on Ubuntu.

I fixed it locally in default.py around line 1029:
elif action==ACTION_SELECT_ITEM:
                    subprocess.Popen('xdotool key Return', shell=True)

new:
subprocess.Popen('xdotool key space', shell=True)

This worked for me.

**Comment by andrewleech** [comment]
Ah, I've never used that remote control functionality baked into the addon, I use my mce remote with the kernel rc driver on ubuntu which makes it appear as a keyboard, so it works just fine directly in chrome.

The keymapping of return is handed in my chrome extension, I set it to reload the page as it was a convenient button to use on my remote for when the netflix stream failed. These keymapping can also be changed by going to the entry in netflixbmc settings for chrome plugin options.

In this instance, based on the default keymappings, your suggested change makes perfect sense.

**Comment by Carst-Tankink** [comment]
It seems that 'Space' needs to be 'space' in c4e3f41 : I haven't tested that theory out, but that is what @walkofdoom reported, and the current version does nothing when pressing the 'Ok' button. (Will check this weekend, if you'd like)
