### ISSUE TITLE
Dependencies not met

### ISSUE THREAD

**Issue by cluttered-code** [andrewleech/plugin.video.netflixbmc#21]
I am trying to install the plugin and it says the dependencies are not met.  There is nothing in the readme about dependencies or how to obtain them.

I found these in the addon.xml
```
<requires>
        <import addon="xbmc.python" version="2.1.0"/>
        <import addon="script.module.requests" version="2.4.3"/>
        <import addon="plugin.program.chrome.launcher" version="1.1.2"/>
        <import addon="script.module.pydevd" version="2.1.0" optional="true"/>
</requires>
```

I have the chrome launcher installed that was required by the original xbmc. I'm not sure where to find the rest of these.

Thanks

**Comment by andrewleech** [comment]
Are you trying to install from my repo? 
See the forum thread for more details: http://forum.kodi.tv/showthread.php?tid=211574
The dependencies should be installed automatically from there.

**Comment by cluttered-code** [comment]
I wasn't installing from the repo.  I just downloaded the zip from here.  I'll do it from the repo. you should add the link to that thread in the README.

Thanks again
