### ISSUE TITLE
[Feature Request] Add "Continue Watching" menu

### ISSUE THREAD

**Issue by PrplHaz4** [andrewleech/plugin.video.netflixbmc#53]
WMC Netflix client has a "Continue Watching" menu that allows you to pick up a show where you left off.  

Currently "Viewing Activity" only takes you to the last episode you actually watched, and it's somewhat difficult to get back to the last show you were watching if it is not already in your queue.

**Comment by rokam** [comment]
After you click on suggestions, there is a continue watching.

**Comment by PrplHaz4** [comment]
Thanks @rokam!  Seems like an odd place for it to me, but I guess I should've looked harder...
