### ISSUE TITLE
Unable to download addon(s) from repo

### ISSUE THREAD

**Issue by TheSwede86** [andrewleech/plugin.video.netflixbmc#71]
`Starting Kodi (17.5 Git:5bd45ab). Platform: Linux ARM (Thumb) 32-bit
Using Release Kodi x32 build
Kodi compiled Oct 28 2017 by GCC 6.2.0 for Linux ARM (Thumb) 32-bit version 3.14.29 (200221)
NOTICE: Running on LibreELEC (community): 8.2.0.1, kernel: Linux ARM 64-bit version 3.14.29`

Hi,

I am unable to download either "Chrome Launcher" or "Netflixbmc", the only thing I get when going into the select add-on itself in the repo is:
Big coverart for the app
A description
"Repository: Unknown"
and the possibility to "Install" but then it does nothing.

Kodi.log here:
https://pastebin.com/ZGJ3HmnW

**Comment by andrewleech** [comment]
Hi, yeah sorry my Netflix plugin broke years ago after a massive change to the way the Netflix site worked and I stopped working on it. 

As such I sotopped my repo service as the level of traffic was hurting my host for no useful purpose.

**Comment by TheSwede86** [comment]
@andrewleech:

Cheers for your reply and also for the work you put in on this project :)

Hope you dont mind I link to another repo for netflixbmc and Kodi v.18 (Leia):
https://github.com/asciidisco/plugin.video.netflix
